crypto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('marketdata/', include('marketdata.urls')),
    path('admin/', admin.site.urls),
]

marketdata/urls.py
from django.urls import path

from . import views

app_name='marketdata'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('currency/<int:pk>/', views.CurrencyView.as_view(), name='currency'),
]

marketdata/models.py
import datetime
from django.db import models


class Currency(models.Model):
    """
    Model the 'currency' format from coinbase as thats where the data is
    coming from
    Example (Bitcoin):
    {
    'id': 'BTC',
    'name': 'Bitcoin',
    'min_size': '0.00000001',
    'status': 'online',
    'message': None,
    'details': {
        'type': 'crypto',
        'symbol': '₿',
        'network_confirmations': 6,
        'sort_order': 3,
        'crypto_address_link': 'https://live.blockcypher.com/btc/address/{{address}}',
        'crypto_transaction_link': 'https://live.blockcypher.com/btc/tx/{{txId}}',
        'push_payment_methods': ['crypto']
        }
    }

    This data only needs to be pulled once. (possibly pull once a week just to
    confirm nothing changes).
    """
    symbol = models.CharField(max_length=10)
    name = models.CharField(max_length=50)

    def __str__(self):
        return f'({self.symbol}) {self.name}'


class Product(models.Model):
    """
    A product is the 'coinbase' product which is listing pairs.

    Ex. BTC-USD is the Bitcoin/US Dollar market
    """
    product_id = models.CharField(max_length=20)
    base_currency = models.ForeignKey(Currency, related_name='base_currency', on_delete=models.CASCADE)
    quote_currency = models.ForeignKey(Currency, related_name='quote_currency', on_delete=models.CASCADE)
    display_name = models.CharField(max_length=20)

    def __str__(self):
        return f'{self.display_name}'


class ProductStatistics(models.Model):
    """
    Hold 24hr statistics on a certain product

    Ex. (Bitcoin)
    {
        'open': '3581.26000000',
        'high': '3614.47000000',
        'low': '3530.84000000',
        'volume': '7802.85353667',
        'last': '3531.94000000',
        'volume_30day': '309826.47342979'
    }
    update this every 10 minutes???
    """
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    open = models.FloatField()
    high = models.FloatField()
    low = models.FloatField()
    volume = models.FloatField()
    last = models.FloatField()
    volume_30day = models.FloatField()
    last_updated = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.product} last updated: {self.last_updated}'

marketdata/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic

from .models import Currency, Product, ProductStatistics


class IndexView(generic.ListView):
    template_name = 'marketdata/index.html'
    context_object_name = 'productstats_list'

    def get_queryset(self):
        """Return most recent stats for each product."""
        products = Product.objects.all()
        most_recent_stats = []
        for product in products:
            ps = ProductStatistics.objects.filter(product=product).order_by('-last_updated')[0]
            most_recent_stats.append(ps)
        return most_recent_stats


class DetailView(generic.DetailView):
    model = Product
    template_name = 'marketdata/detail.html'


class CurrencyView(generic.DetailView):
    model = Currency
    template_name = 'marketdata/currency.html'

marketdata/templates/marketdata/currency.html
<!doctype html>
<title>crypto.</title>
<meta charset="utf-8">
<meta name="description" content="24hr crypto stats from coinbase">
<meta name="author" content="joe">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'marketdata/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'skeleton.css' %}">

<div class=container>
  <div id=header>
    <strong id=title>24 Hour Cryptocurrency Statistics from Coinbase Pro </strong>
    <p> data updated every 10 minutes </p>
    <hr class=hr>
  </div>
</div>
<h1> Currency: {{ currency }}</h1>

marketdata/templates/marketdata/detail.html
<!doctype html>
<title>crypto.</title>
<meta charset="utf-8">
<meta name="description" content="24hr crypto stats from coinbase">
<meta name="author" content="joe">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'marketdata/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'skeleton.css' %}">

<div class=container>
  <div id=header>
    <strong id=title>24 Hour Cryptocurrency Statistics from Coinbase Pro </strong>
    <p> data updated every 10 minutes </p>
    <hr class=hr>
  </div>
</div>
<h1> Product: {{ product.product_id }}</h1>
<h1> <a href="{% url 'marketdata:currency' product.base_currency.id %}">Base Currency: {{ product.base_currency }}</a></h1>
<h1> <a href="{% url 'marketdata:currency' product.quote_currency.id %}">Quote Currency: {{ product.quote_currency }}</a></h1>
<h1> Display Name: {{ product.display_name }}</h1>

marketdata/templates/marketdata/index.html
<!doctype html>
<title>crypto.</title>
<meta charset="utf-8">
<meta name="description" content="24hr crypto stats from coinbase">
<meta name="author" content="joe">
<meta name="viewport" content="width=device-width, initial-scale=1">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'marketdata/style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'normalize.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'skeleton.css' %}">

<div class=container>
  <div id=header>
    <strong id=title>24 Hour Cryptocurrency Statistics from Coinbase Pro </strong>
    <p> data updated every 10 minutes </p>
    <hr class=hr>
  </div>
</div>
{% if productstats_list %}
  <div id=table-container>
    <table>
      <tr>
        <th>Listing</th>
        <th>Open</th>
        <th>High</th>
        <th>Low</th>
        <th>Volume</th>
        <th>Last</th>
        <th>30 Day Volume</th>
        <th>Last Updated</th>
      </tr>
      {% for stat in productstats_list %}
        <tr>
          <td><a href="{% url 'marketdata:detail' stat.product.id %}">{{ stat.product }}</a></td>
          <th>{{ stat.open }}</th>
          <th>{{ stat.high }}</th>
          <th>{{ stat.low }}</th>
          <th>{{ stat.volume }}</th>
          <th>{{ stat.last }}</th>
          <th>{{ stat.volume_30day }}</th>
          <th>{{ stat.last_updated }}</th>
        </tr>
      {% endfor %}
    </table>
  </div>
{% else %}
    <p>No statistics are available.</p>
{% endif %}